projects:
  STAGING-CRM-appsyncApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-1
        apiId: vco4p4fhkng7voxzcdgwteobvi
        maxDepth: 3
extensions:
  amplify:
    version: 3
